sudo: false
node_js:
  - "0.12"
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - libasound2-dev
language: cpp
compiler:
  - gcc
  - clang
before_script:
  - git submodule update --init --recursive
script: node make.js --kha . --from Tests/Empty --compile
