sudo: false
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - libasound2-dev
language: cpp
compiler:
  - gcc
  - clang
before_script:
  - git submodule update --init --recursive
  - git clone https://github.com/ktxsoftware/iojs_bin.git
  - iojs_bin/copysysbin.sh
script: iojs_bin/iojs make.js --kha . --from Tests/Empty --compile
