sudo: false
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libasound2-dev
language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-25.0.2
    - android-25
    - extra
before_script:
  - git submodule update --init --recursive
  - git clone https://github.com/ktxsoftware/nodejs_bin.git --depth 1
  - nodejs_bin/copysysbin.sh
  - git clone https://github.com/RobDangerous/Android-Licenses.git
  - mkdir -p "$ANDROID_HOME/licenses"
  - cp ./Android-Licenses/ "$ANDROID_HOME/licenses/"
script:
  - nodejs_bin/node make.js html5 --kha . --from Tests/Empty
  - nodejs_bin/node make.js krom --kha . --from Tests/Empty
  - nodejs_bin/node make.js flash --kha . --from Tests/Empty
  - nodejs_bin/node make.js --kha . --from Tests/Empty --compile
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nodejs_bin/node make.js android --kha . --from Tests/Empty --compile; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nodejs_bin/node make.js android-native --kha . --from Tests/Empty --compile; fi