sudo: false
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libasound2-dev
      - gcc-4.9
      - g++-4.9
    update-alternatives:
      - install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
      - install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
language: cpp
compiler:
  - gcc
  - clang
before_script:
  - git submodule update --init --recursive
  - git clone https://github.com/ktxsoftware/nodejs_bin.git
  - nodejs_bin/copysysbin.sh
script: nodejs_bin/node make.js --kha . --from Tests/Empty --compile
