sudo: false
addons:
  apt:
    packages:
    - libasound2-dev
language: cpp
compiler:
  - gcc
  - clang
before_script:
  - git submodule update --init --recursive
  - git clone https://github.com/ktxsoftware/iojs_bin.git
script: iojs_bin/iojs-linux64 make.js --kha . --from Tests/Empty --compile
