sudo: false
language: cpp
compiler:
  - gcc
  - clang
before_script:
  - git clone https://github.com/ktxsoftware/iojs_bin.git
script: iojs_bin/iojs-linux64 make.js --kha . --from Tests/Empty --compile
